#!/bin/bash
 
while getopts “p:o:n:u:i:” opts; do
        case $opts in
                p)
                port=$OPTARG;;
                o)
                origin=$OPTARG;;
                n)
                name=$OPTARG;;
                u)
                username=$OPTARG;;
                i)
                keyfile=$OPTARG;;
        esac
done
 
 
dns_server="p5-dns.5700.network"
ssh -i $keyfile $username@$dns_server nohup ./dnsserver -p $port -n $name &
 
 
declare -a replica_servers=("p5-http-a.5700.network" "p5-http-b.5700.network" "p5-http-c.5700.network" "p5-http-d.5700.network" "p5-http-e.5700.network" "p5-http-f.5700.network" "p5-http-g.5700.network");
 
servers_length=${#replica_servers[@]}
 
for (( i = 0; i < ${servers_length}; i++ ));
do
        ssh -i $keyfile $username@${replica_servers[$i]} nohup ./httpserver -p $port -o $origin &
done